### ISSUE TITLE
Module 'tagui' has no attribute 'init' - user named script as tagui.py

### ISSUE THREAD

**Issue by lchojnowski** [tebelorg/TagUI-Python#64]
After installing pip package, i cannot really import the library:

```
[23:54:26] lchojnowski:ing git:(master*) $ python3
Python 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tagui as t
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lchojnowski/Code/rpipy/ing/tagui.py", line 10, in <module>
    t.init()
AttributeError: module 'tagui' has no attribute 'init'
>>> 
```

My versions are:

```
[23:56:40] lchojnowski:ing git:(master*) $ python3 --version
Python 3.7.3
[23:56:45] lchojnowski:ing git:(master*) $ pip3 --version
pip 19.0.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
[23:56:49] lchojnowski:ing git:(master*) $ 
```

**Comment by kensoh** [comment]
Can you try to list the installed packages with below command to see if tagui is there?

```
pip3 list
```

Your folder does no look like the usual folder where Python packages are installed -
```
/Users/lchojnowski/Code/rpipy/ing/tagui.py
```

For example, mine is installed here -
```
'/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tagui.py'
```

**Comment by lchojnowski** [comment]
Hey, here it is:

```
[23:56:49] lchojnowski:ing git:(master*) $ pip3 list | grep tagui
tagui           1.13.0   
[5:39:02] lchojnowski:ing git:(master*) $ 
```

The path of `/Users/lchojnowski/Code/rpipy/ing/tagui.py` is path of my script not the tagui package (i've named the script `tagui.py`).

**Comment by kensoh** [comment]
Oh I know why now lol. This is a accidental mistake. When you run python command and do an `import tagui as t`, it will see if there is a tagui.py file in the same directory. If there is, by priority it will try to import that tagui.py as the module, instead of whatever that is installed on your Python environment using pip or pip2 or pip3. To fix this error, name your script with another name other than tagui.py. You see below, I can replicate this issue by creating a script called tagui.py -

```
Tebel:Desktop kensoh$ python3 tagui.py
Traceback (most recent call last):
  File "tagui.py", line 1, in <module>
    import tagui as t
  File "/Users/kensoh/Desktop/tagui.py", line 2, in <module>
    t.init()
AttributeError: module 'tagui' has no attribute 'init'
```

**Comment by lchojnowski** [comment]
After renaming to `tagui_test.py` i  is still not working:

```
[19:16:42] lchojnowski:ing git:(master*) $ python3 tagui_test.py 
Traceback (most recent call last):
  File "tagui_test.py", line 6, in <module>
    import tagui as t
ImportError: bad magic number in 'tagui': b'\x03\xf3\r\n'
[19:16:50] lchojnowski:ing git:(master*) $ 
```

Below are my versions:

```
[19:18:14] lchojnowski:ing git:(master*) $ pip3 --version
pip 19.0.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
[19:18:22] lchojnowski:ing git:(master*) $ pip3 list | grep tagui
tagui           1.13.0   
[19:18:29] lchojnowski:ing git:(master*) $ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95
[19:19:09] lchojnowski:ing git:(master*) $ 
```

**Comment by lchojnowski** [comment]
And the verbose output:

```
[19:26:15] lchojnowski:ing git:(master*) $ python3 -v demo.py
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'zipimport' # <class '_frozen_importlib.BuiltinImporter'>
# installed zipimport hook
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/__pycache__/__init__.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/__init__.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/__pycache__/__init__.cpython-37.pyc'
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/codecs.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/codecs.cpython-37.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x104ac2320>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/__pycache__/aliases.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/aliases.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/__pycache__/aliases.cpython-37.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x104ad1e48>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x104abdd68>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/__pycache__/utf_8.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/utf_8.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/__pycache__/utf_8.cpython-37.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x104ae3b70>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/__pycache__/latin_1.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/latin_1.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/encodings/__pycache__/latin_1.cpython-37.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x104ae65f8>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/io.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/io.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/io.cpython-37.pyc'
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/abc.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/abc.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/abc.cpython-37.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x104ae6ba8>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x104ae67f0>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/_bootlocale.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_bootlocale.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/_bootlocale.cpython-37.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0x104aed208>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/site.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/site.cpython-37.pyc'
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/os.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/os.cpython-37.pyc'
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/stat.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/stat.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/stat.cpython-37.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x104b46b70>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/posixpath.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/posixpath.cpython-37.pyc'
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/genericpath.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/genericpath.cpython-37.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x104b50668>
import 'posixpath' # <_frozen_importlib_external.SourceFileLoader object at 0x104b4a2e8>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/_collections_abc.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_collections_abc.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/_collections_abc.cpython-37.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x104b50c88>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x104af7860>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/_sitebuiltins.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_sitebuiltins.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/_sitebuiltins.cpython-37.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x104af7c18>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/__pycache__/sitecustomize.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sitecustomize.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/__pycache__/sitecustomize.cpython-37.pyc'
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/re.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/re.cpython-37.pyc'
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/enum.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/enum.cpython-37.pyc'
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/types.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/types.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/types.cpython-37.pyc'
import 'types' # <_frozen_importlib_external.SourceFileLoader object at 0x104ba1748>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'enum' # <_frozen_importlib_external.SourceFileLoader object at 0x104b91860>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/sre_compile.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_compile.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/sre_compile.cpython-37.pyc'
import '_sre' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/sre_parse.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_parse.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/sre_parse.cpython-37.pyc'
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/sre_constants.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_constants.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/sre_constants.cpython-37.pyc'
import 'sre_constants' # <_frozen_importlib_external.SourceFileLoader object at 0x104be48d0>
import 'sre_parse' # <_frozen_importlib_external.SourceFileLoader object at 0x104bb5e10>
import 'sre_compile' # <_frozen_importlib_external.SourceFileLoader object at 0x104ba77b8>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/functools.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/functools.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/functools.cpython-37.pyc'
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__pycache__/__init__.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__init__.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__pycache__/__init__.cpython-37.pyc'
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/operator.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/operator.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/operator.cpython-37.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at 0x104c1f9b0>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/keyword.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/keyword.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/keyword.cpython-37.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0x104c2ab00>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/heapq.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/heapq.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/heapq.cpython-37.pyc'
# extension module '_heapq' loaded from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_heapq.cpython-37m-darwin.so'
# extension module '_heapq' executed from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_heapq.cpython-37m-darwin.so'
import '_heapq' # <_frozen_importlib_external.ExtensionFileLoader object at 0x104c2c940>
import 'heapq' # <_frozen_importlib_external.SourceFileLoader object at 0x104c2c438>
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/reprlib.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/reprlib.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/reprlib.cpython-37.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at 0x104c2ca20>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object at 0x104bfcdd8>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at 0x104bea978>
# /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/copyreg.cpython-37.pyc matches /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copyreg.py
# code object from '/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/__pycache__/copyreg.cpython-37.pyc'
import 'copyreg' # <_frozen_importlib_external.SourceFileLoader object at 0x104c23dd8>
import 're' # <_frozen_importlib_external.SourceFileLoader object at 0x104b8c780>
import 'sitecustomize' # <_frozen_importlib_external.SourceFileLoader object at 0x104b8c5f8>
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x104af3518>
Python 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
# bad magic number in 'tagui': b'\x03\xf3\r\n'
Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    import tagui as t
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1005, in get_code
  File "<frozen importlib._bootstrap_external>", line 458, in _classify_pyc
ImportError: bad magic number in 'tagui': b'\x03\xf3\r\n'
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# destroy tagui
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.__interactivehook__
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing sys
# cleanup[2] removing builtins
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _imp
# cleanup[2] removing _thread
# cleanup[2] removing _warnings
# cleanup[2] removing _weakref
# cleanup[2] removing zipimport
# cleanup[2] removing _frozen_importlib_external
# cleanup[2] removing _io
# cleanup[2] removing marshal
# cleanup[2] removing posix
# cleanup[2] removing encodings
# destroy encodings
# cleanup[2] removing codecs
# cleanup[2] removing _codecs
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing _signal
# cleanup[2] removing __main__
# destroy __main__
# cleanup[2] removing encodings.latin_1
# cleanup[2] removing io
# destroy io
# cleanup[2] removing abc
# cleanup[2] removing _abc
# cleanup[2] removing _bootlocale
# destroy _bootlocale
# cleanup[2] removing _locale
# cleanup[2] removing site
# destroy site
# cleanup[2] removing os
# cleanup[2] removing stat
# cleanup[2] removing _stat
# cleanup[2] removing posixpath
# cleanup[2] removing genericpath
# cleanup[2] removing os.path
# cleanup[2] removing _collections_abc
# cleanup[2] removing _sitebuiltins
# cleanup[2] removing sitecustomize
# destroy sitecustomize
# cleanup[2] removing re
# destroy re
# cleanup[2] removing enum
# cleanup[2] removing types
# destroy types
# cleanup[2] removing _collections
# cleanup[2] removing sre_compile
# cleanup[2] removing _sre
# cleanup[2] removing sre_parse
# cleanup[2] removing sre_constants
# destroy sre_constants
# cleanup[2] removing functools
# cleanup[2] removing _functools
# cleanup[2] removing collections
# destroy collections
# cleanup[2] removing operator
# destroy operator
# cleanup[2] removing _operator
# cleanup[2] removing keyword
# destroy keyword
# cleanup[2] removing heapq
# cleanup[2] removing _heapq
# cleanup[2] removing itertools
# cleanup[2] removing reprlib
# destroy reprlib
# cleanup[2] removing copyreg
# destroy zipimport
# destroy _signal
# destroy _sitebuiltins
# destroy abc
# destroy posixpath
# destroy _stat
# destroy genericpath
# destroy os
# destroy stat
# destroy enum
# destroy sre_compile
# destroy functools
# destroy _locale
# destroy copyreg
# destroy sre_parse
# destroy _sre
# destroy _abc
# destroy _functools
# destroy _collections_abc
# destroy heapq
# destroy _collections
# destroy _operator
# destroy _heapq
# destroy itertools
# cleanup[3] wiping _frozen_importlib
# destroy _frozen_importlib_external
# cleanup[3] wiping _imp
# cleanup[3] wiping _thread
# cleanup[3] wiping _warnings
# cleanup[3] wiping _weakref
# cleanup[3] wiping _io
# cleanup[3] wiping marshal
# cleanup[3] wiping posix
# cleanup[3] wiping codecs
# cleanup[3] wiping _codecs
# cleanup[3] wiping encodings.aliases
# cleanup[3] wiping encodings.utf_8
# cleanup[3] wiping encodings.latin_1
# cleanup[3] wiping sys
# cleanup[3] wiping builtins
```

**Comment by kensoh** [comment]
I haven't come across anything like this. Can you type python to enter the Python interactive mode?

After that type the following to see what happens. Below are my outputs for Python 2 and 3. So far, no other users have encountered the issue that you are facing.

```
Python 2.7.10 (default, Feb 22 2019, 21:55:15) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tagui as t
>>> t.__file__
'/Library/Python/2.7/site-packages/tagui.pyc'
>>> t.init()
True
```
```
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tagui as t
>>> t.__file__
'/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tagui.py'
>>> t.init()
True
```

**Comment by kensoh** [comment]
(above is running on Mac, same sw_vers version as yours)

**Comment by kensoh** [comment]
Adding on, there is no reference to x03 or xf3 special characters in the source code of tagui.py, so I'm not sure what could have gave you the error message above when you import tagui as t -

```
ImportError: bad magic number in 'tagui': b'\x03\xf3\r\n'
```

**Comment by kensoh** [comment]
Closing issue for now until further inputs
